# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT

name = "Mod Batch"
version = "1.0.0"
extension = "bat"
interpreter = "cmd /c"

[dev]
strategy = "interpreter"
