# Copyright (c) 2026 The Frontier Framework Authors  
# SPDX-License-Identifier: Apache-2.0 OR MIT

name = "Mod GCC"
version = "1.0.0"
extension = "c"
suppress_window = true

[dev]
strategy = "build"

[build]
command = "gcc %IN% -o %OUT%"
