# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT

name = "Mod GPP"
version = "1.0.0"
extension = "cpp"
suppress_window = true

[dev]
strategy = "build"

[build]
command = "g++ %IN% -o %OUT%"