# Copyright (c) 2026 The Frontier Framework Authors  
# SPDX-License-Identifier: Apache-2.0 OR MIT

name = "Mod NodeJS"
version = "1.0.0"
extension = "js"
interpreter = "node"

[dev]
strategy = "interpreter"