name = "Mod Python"
version = "1.0.0"
extension = "py"
interpreter = "python"
suppress_window = true

# [build]  <-- REMOVIDO!
# O Manager vai detectar que não tem build e fará uma cópia segura automaticamente.

[dev]

strategy = "interpreter"
